nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.5.3.cjs

compressionLevel: mixed

enableGlobalCache: false

nmMode: hardlinks-local

supportedArchitectures:
  os: [darwin, linux, win32]
  cpu: [x64, arm64]

enableTelemetry: false
